Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'CheckBoxFilterOPTIONLIST' data form
''' </summary>
Partial Public Class [CheckBoxFilterOPTIONLISTUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _checked As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _checked = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _name = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        _id.Enabled = False
        Me.Fields.Add(_id)
        '
        '_checked
        '
        _checked.Name = "CHECKED"
        _checked.Caption = "CHECKED"
        Me.Fields.Add(_checked)
        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "NAME"
        _name.Enabled = False
        Me.Fields.Add(_name)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _id
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [CHECKED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _checked
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _name
        End Get
    End Property
    
End Class
