Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Multi-Select Demo List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("4671ebf3-1118-4194-9c74-c670da034e26", "Constituent")>
Partial Public Class [MultiSelectDemoListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the TRANSACTIONTYPEFILTERMODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum TRANSACTIONTYPEFILTERMODES As Integer
        [AllTransactionTypes] = 0
        [SelectedTransactionTypes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _transactiontypefiltermode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of TRANSACTIONTYPEFILTERMODES)
    Private WithEvents _transactiontypecodes As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MultiSelectDemoListTRANSACTIONTYPECODESUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _transactiontypefiltermode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of TRANSACTIONTYPEFILTERMODES)
        _transactiontypecodes = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MultiSelectDemoListTRANSACTIONTYPECODESUIModel)

        MyBase.DataListId = New System.Guid("4671ebf3-1118-4194-9c74-c670da034e26")
        MyBase.ContextRecordType = "Constituent"
        MyBase.UserInterfaceUrl = "browser/htmlforms/multiselectdemo/MultiSelectDemoList.html"

        '
        '_transactiontypefiltermode
        '
        _transactiontypefiltermode.Name = "TRANSACTIONTYPEFILTERMODE"
        _transactiontypefiltermode.Caption = "Transaction types"
        _transactiontypefiltermode.Required = True
        _transactiontypefiltermode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of TRANSACTIONTYPEFILTERMODES) With {.Value = TRANSACTIONTYPEFILTERMODES.[AllTransactionTypes], .Translation = "All transaction types"})
        _transactiontypefiltermode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of TRANSACTIONTYPEFILTERMODES) With {.Value = TRANSACTIONTYPEFILTERMODES.[SelectedTransactionTypes], .Translation = "Selected transaction types"})
        _transactiontypefiltermode.Value = TRANSACTIONTYPEFILTERMODES.[AllTransactionTypes]
        Me.Fields.Add(_transactiontypefiltermode)
        '
        '_transactiontypecodes
        '
        _transactiontypecodes.Name = "TRANSACTIONTYPECODES"
        _transactiontypecodes.Caption = "Transaction type"
        _transactiontypecodes.Visible = False
        Me.Fields.Add(_transactiontypecodes)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Transaction types
    ''' </summary>
    <System.ComponentModel.Description("Transaction types")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [TRANSACTIONTYPEFILTERMODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of TRANSACTIONTYPEFILTERMODES)
        Get
            Return _transactiontypefiltermode
        End Get
    End Property
    
    ''' <summary>
    ''' Transaction type
    ''' </summary>
    <System.ComponentModel.Description("Transaction type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [TRANSACTIONTYPECODES]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of MultiSelectDemoListTRANSACTIONTYPECODESUIModel)
        Get
            Return _transactiontypecodes
        End Get
    End Property
    
End Class
